[package]
name = "c--compiler"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
nonstandard-style = "allow"

[dependencies]
lazy_static = "1.4.0"